# config/application.yml
defaults: &defaults
  # 微信相关
  WECHAT:
    WECHAT_TOKEN: eshop_token
    # 临时二维码请求参数
    TEMPORARY_QRCODE_POST_PARAMS:
      expire_seconds:
      action_name: "QR_SCENE"
      action_info:
        scene:
          scene_id: 123
    FOREVER_QRCODE_POST_PARAMS:
      QR_LIMIT_SCENE:
        QRCODE_POST_PARAMS:
          action_name: "QR_LIMIT_SCENE"
          action_info:
            scene:
              scene_id: 123
      QR_LIMIT_STR_SCENE:
        QRCODE_POST_PARAMS:
          action_name: "QR_LIMIT_STR_SCENE"
          action_info:
            scene:
              scene_str: "123"

  # 系统图片分类定义
  PICTURES_CATEGORY:
    PRODUCT:
      轮播: 1
      方正: 2
      详情: 3
    STORE:
      广告轮播: 100
      新日新品: 101
      推荐: 102
      火爆: 103
      团购: 104
      热销: 105

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults