# config/application.yml
defaults: &defaults
  # http header设置
  REQUEST_HEADERS:
    CONTENT_TYPE_KEY: "Content-Type"
    CONTENT_TYPE_VALUE:
      JSON: "application/json"
      XML: "application/xml"

  # 订单状态
  ORDER:
    STATUS:
      CANCEL: 0
      PREPAY: 1
      PAID: 2
      DELIVERED: 3
      COMPLETED: 4
    EXPIRE_TIME: "#{10*60}"

  # 微信相关
  WECHAT:
    # 通过code换取网页授权access_token
    PAGE_ACCESS_TOKEN:
      # 拉取用户信息(需scope为 snsapi_userinfo)
      GET_USERINFO:
        URL: "https://api.weixin.qq.com/sns/userinfo"
        QUERY_PARAMS:
          access_token: ""
          openid: ""
          lang: "zh_CN"

      # 检验授权凭证（access_token）是否有效
      AUTH_ACCESS_TOKEN:
        URL: "https://api.weixin.qq.com/sns/auth"
        QUERY_PARAMS:
          access_token: ""
          openid: ""

      SCOPE:
        snsapi_userinfo: "snsapi_userinfo"
        snsapi_base: "snsapi_base"

      URL: "https://api.weixin.qq.com/sns/oauth2/access_token"
      QUERY_PARAMS:
        appid: ""
        secret: ""
        code: ""
        grant_type: "authorization_code"

    # 需要跟公众号服务器设置中的值一致
    WECHAT_TOKEN: "eshop_token"
    CREATE_QRCODE_URL: "https://api.weixin.qq.com/cgi-bin/qrcode/create"
    # 临时二维码请求参数
    TEMPORARY_QRCODE_POST_PARAMS:
      expire_seconds:
      action_name: "QR_SCENE"
      action_info:
        scene:
          scene_id: 123
    # 永久二维码请求参数
    FOREVER_QRCODE_POST_PARAMS:
      QRCODE_POST_PARAMS:
        action_name: "QR_LIMIT_SCENE"
        action_info:
          scene:
            scene_id: 123
      QRCODE_POST_PARAMS_STR:
        action_name: "QR_LIMIT_STR_SCENE"
        action_info:
          scene:
            scene_str: "123"

    # WXPAY
    UNIFIEDORDER_URL: "https://api.mch.weixin.qq.com/pay/unifiedorder"

    # 网页端调起支付API请求参数
    JSAPI_PAY_SIGNATURE_PARAMS:
      jsapi_ticket: ""
      url: ""
      timestamp: ""
      noncestr: ""

    # 获取access_token请求及参数
    ACCESS_TOKEN:
      URL: "https://api.weixin.qq.com/cgi-bin/token"
      QUERY_PARAMS:
        grant_type: "client_credential"
        appid: ""
        secret: ""

    # 定义微信有过期特性的数据名称
    EXPIRE_DATA:
      ACCESS_TOKEN: "access_token"
      JSAPI_TICKET: "jsapi_ticket"

  # 系统图片分类定义
  PICTURES_CATEGORY:
    PRODUCT:
      轮播: 1
      方正: 2
      详情: 3
      全尺寸: 4
    STORE:
      广告轮播: 100
      新日新品: 101
      推荐: 102
      火爆: 103
      团购: 104
      热销: 105

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults