# config/application.yml
defaults: &defaults
  WITHDRAW:
    APPLYING: 0
    PAID: 1
  CUSTOMER_ACCOUNT:
    TRANSACTION_TYPE:
      COMMISSION: 0
  HOME_URL: "http://www.yiyunma.com/#/home"
  DISTRIBUTION_LEVEL: 3   # 设置分销等级
  DISTRIBUTOR_LEVEL:
    ZERO: 0
    ONE: 1
  DISTRIBUTION_RULES:
    ANYONE: 0
    RULE1: 1
    RULE2: 2
  DISTRIBUTION_QRCODE:
    CLI_CREATE_QRCODE:
      URL: "https://cli.im/api/qrcode/code"
      QUERY_PARAMS:
        text: ""

  # http header设置
  REQUEST_HEADERS:
    CONTENT_TYPE_KEY: "Content-Type"
    CONTENT_TYPE_VALUE:
      JSON: "application/json"
      XML: "application/xml"

  # 订单状态
  ORDER:
    STATUS:
      CANCEL: 0     # 已取消
      PREPAY: 1     # 未付款
      PAID: 2       # 已付款
      DELIVERED: 3  # 已发货
      COMPLETED: 4  # 已完成
      REFUNDING: 5  # 退款中
      REFUND: 6     # 退款完成
    EXPIRE_TIME: "#{10*60}"

  # 微信相关
  WECHAT:
    # 微信网页授权url
    WX_OAUTH2:
      URL: "https://open.weixin.qq.com/connect/oauth2/authorize"
      QUERY_PARAMS:
        appid: ""
        redirect_uri: "http%3a%2f%2fwww.yiyunma.com%2fapi%2fv1%2fwx_page_authorization"
        response_type: "code"
        scope: "snsapi_base"
        state: ""

    # 微信消息管理
    WXMESSAGES:
      EVENT:
        SUBSCRIBE:
          KEY: "subscribe"
          TEXT: "欢迎关注！熊笨熊商城，专注于为广大消费者提供能够放心，优质，无害的有机健康食品，100%专柜正品，七天退换，成为消费者于生产者之间的桥梁。"
          XML:
            ToUserName: true
            FromUserName: true
            CreateTime: false
            MsgType: true
            Content: true
        UNSUBSCRIBE:
          KEY: "unsubscribe"
          TEXT: ""
    WXPAY_NOTIFY:
      RETURN_CODE:
        OK: "<xml>
               <return_code><![CDATA[SUCCESS]]></return_code>
               <return_msg><![CDATA[OK]]></return_msg>
             </xml>"
    # 通过code换取网页授权access_token
    PAGE_ACCESS_TOKEN:
      # 拉取用户信息(需scope为 snsapi_userinfo)
      GET_USERINFO:
        URL: "https://api.weixin.qq.com/sns/userinfo"
        QUERY_PARAMS:
          access_token: ""
          openid: ""
          lang: "zh_CN"

      # 检验授权凭证（access_token）是否有效
      AUTH_ACCESS_TOKEN:
        URL: "https://api.weixin.qq.com/sns/auth"
        QUERY_PARAMS:
          access_token: ""
          openid: ""

      SCOPE:
        snsapi_userinfo: "snsapi_userinfo"
        snsapi_base: "snsapi_base"

      URL: "https://api.weixin.qq.com/sns/oauth2/access_token"
      QUERY_PARAMS:
        appid: ""
        secret: ""
        code: ""
        grant_type: "authorization_code"

    # 需要跟公众号服务器设置中的值一致
    WECHAT_TOKEN: "eshop_token"
    CREATE_QRCODE_URL: "https://api.weixin.qq.com/cgi-bin/qrcode/create"
    SHOW_QRCODE:
      URL: "https://mp.weixin.qq.com/cgi-bin/showqrcode"
      QUERY_PARAMS:
        ticket: ""
    # 临时二维码请求参数
    TEMPORARY_QRCODE_POST_PARAMS:
      expire_seconds:
      action_name: "QR_SCENE"
      action_info:
        scene:
          scene_id: 123
    # 永久二维码请求参数
    FOREVER_QRCODE_POST_PARAMS:
      QRCODE_POST_PARAMS:
        action_name: "QR_LIMIT_SCENE"
        action_info:
          scene:
            scene_id: 123
      QRCODE_POST_PARAMS_STR:
        action_name: "QR_LIMIT_STR_SCENE"
        action_info:
          scene:
            scene_str: "123"

    # WXPAY
    UNIFIEDORDER_URL: "https://api.mch.weixin.qq.com/pay/unifiedorder"

    # 网页端调起支付API请求参数
    JSAPI_PAY_SIGNATURE_PARAMS:
      jsapi_ticket: ""
      url: ""
      timestamp: ""
      noncestr: ""

    # 获取access_token请求及参数
    ACCESS_TOKEN:
      URL: "https://api.weixin.qq.com/cgi-bin/token"
      QUERY_PARAMS:
        grant_type: "client_credential"
        appid: ""
        secret: ""

    # 定义微信有过期特性的数据名称
    EXPIRE_DATA:
      ACCESS_TOKEN: "access_token"
      JSAPI_TICKET: "jsapi_ticket"

    # 微信创建公众号菜单接口
    CREATE_WXMENU_URL: "https://api.weixin.qq.com/cgi-bin/menu/create"

  # 系统图片分类定义
  PICTURES_CATEGORY:
    PRODUCT:
      轮播图片: 1
      商品图片: 2
      详情图片: 3
    STORE:
      广告轮播: 100
      新日新品: 101
      推荐: 102
      火爆: 103
      团购: 104
      热销: 105

  # 产品分类id定义
  PRODUCT_CATEGORY:
    HOME: 2
    XIAOGUO: 3
    LINGSHI: 4
    JIANGUO: 5
    YANGSHENG: 6
    JINGKOU: 7
    TECHAN: 8

  # 定义商品状态
  PRODUCT_STATUS:
    UNDERCARRIAGE: 0
    GROUNDING: 1

#  # 定义商品属性
#  PRODUCT_PROPERTY:
#    SINGLE: 0
#    TINY: 1
#    BIG: 2

  # 定义价格和价格计量单位
  PRICE:
    JIN: 0
    GE: 1
    FEN: 2
    HE: 3
    XIANG: 4

  # 定义广告分类和状态
  ADVERT:
    STATUS:
      NOT_PUT: 0
      PUTTING: 1
      WITHDRAWED: 2
    CATEGORY:
      HOME_TOP: 0

  # 自动计算类别定义
  COMPUTE:
    CATEGORY:
      SINGLE_SETMEAL: 0 # 单品
      PERSONAL_SETMEAL: 1 # 个人套餐
      TEAM_SETMEAL: 2  # 团队套餐推荐

  # 购物车项属性常量定义
  CART_OR_ITEM:
    PROPERTY:
      CART_ITEM: 0            # 购物车详情项
      ORDER_DETAILS_ITEM: 1   # 订单详情项

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults