defaults: &defaults
  WECHAT:
    appid: "wx0958a9b801758435" # AppID
    secret: "cb259a14f584f8951bf9ee1f63472538" # AppSecret
    PAY:
      sign_key: "1234567890qwertyuiopasdfghjklzxc"
      unifiedorder_product_details:
        goods_id:
          KEY: "goods_id"
          VALUE: ""
#        wxpay_goods_id:
#          KEY: "wxpay_goods_id"
#          VALUE: ""
        goods_name:
          KEY: "goods_name"
          VALUE: ""
        quantity:
          KEY: "quantity"
          VALUE: ""
        price:
          KEY: "price"
          VALUE: ""
      unifiedorder: # 详细参数说明请查看官方文档 https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1
        appid: "wx0958a9b801758435" #String(32)
        mch_id: "1423683502" #String(32)
#        device_info: "WEB" #String(32)
        nonce_str: "" #String(32)
        sign: "" #String(32)
#        sign_type: "MD5" #String(32)
        body: "熊笨熊商城" #String(128)
#        detail: #String(6000)
#          goods_detail: []
#        attach: "" #String(127)
        out_trade_no: "" #String(32)
#        fee_type: "CNY" #String(16)
        total_fee: 0 # Int 备注：订单总金额，单位为分.
        spbill_create_ip: "139.196.205.1" #String(16) 备注：APP和网页支付提交用户端ip，Native支付填调用微信支付API的机器IP。
#        time_start: "" #String(14)
#        time_expire: "" #String(14)
#        goods_tag: "WXG" #String(32)
        notify_url: "http://www.yiyunma.com/api/v1/wxpay" #String(256)
        trade_type: "JSAPI" #String(16)
#        product_id: "" #String(32)
#        limit_pay: "" #String(32)
        openid: "" #String(128)

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults