defaults: &defaults
  DEFAULT_PASSWORD: '1234'
  ORDER_PRINT:
    PRINTCENTER_365_S2:
      URL: 'http://open.printcenter.cn:8080/addOrder'
      INFO:
        deviceNo: 'kdt2100561'
        key: 'd7bb7'
        printContent: ""
        times: 1
  WECHAT:
    DOMAIN: "http://www.dangxiaweb.com"
    appid: "wxb406f87dd0f6f63e" # AppID
    secret: "6bab14db16de21d0fea516cdef8e281e" # AppSecret
    PAY:
      sign_key: "6glhe1jXMe3Aqnhj6BHjNZxH96zm6E2A"
      unifiedorder_product_details:
        goods_id:
          KEY: "goods_id"
          VALUE: ""
#        wxpay_goods_id:
#          KEY: "wxpay_goods_id"
#          VALUE: ""
        goods_name:
          KEY: "goods_name"
          VALUE: ""
        quantity:
          KEY: "quantity"
          VALUE: ""
        price:
          KEY: "price"
          VALUE: ""
      unifiedorder: # 详细参数说明请查看官方文档 https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1
        appid: "wxb406f87dd0f6f63e" #String(32)
        mch_id: "1452854002" #String(32)
#        device_info: "WEB" #String(32)
        nonce_str: "" #String(32)
        sign: "" #String(32)
#        sign_type: "MD5" #String(32)
        body: "生鲜小镇" #String(128)
#        detail: #String(6000)
#          goods_detail: []
#        attach: "" #String(127)
        out_trade_no: "" #String(32)
#        fee_type: "CNY" #String(16)
        total_fee: 0 # Int 备注：订单总金额，单位为分.
        spbill_create_ip: "116.62.6.81" #String(16) 备注：APP和网页支付提交用户端ip，Native支付填调用微信支付API的机器IP。
#        time_start: "" #String(14)
#        time_expire: "" #String(14)
#        goods_tag: "WXG" #String(32)
        notify_url: "http://www.dangxiaweb.com/api/v1/wxpay" #String(256)
        trade_type: "JSAPI" #String(16)
#        product_id: "" #String(32)
#        limit_pay: "" #String(32)
        openid: "" #String(128)

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults