defaults: &defaults
  COMMON:
    OK:
      code: 0
      message: successful
    FAILED:
      code: -1
      message: failed

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults